config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cmv.server:
      branch: main
      repo: https://github.com/cessda/cessda.cmv.server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cmv.server git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-pear-foxhound.sh
        container: qc.acc_homey-denim-angora
  QC.Doc:
    repos:
      github.com/cessda/cessda.cmv.server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-salmon-robin.sh
        container: qc.doc_ugly-auburn-turkey
      github.com/cessda/cessda.cmv.server git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-saffron-zebra.sh
        container: qc.doc_wiggy-lavender-angora
      github.com/cessda/cessda.cmv.server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-maroon-reindeer.sh
        container: qc.doc_pretty-apricot-hornet
  QC.Lic:
    repos:
      github.com/cessda/cessda.cmv.server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-blue-insect.sh
        container: qc.lic_scummy-indigo-wolverine
  QC.Met:
    repos:
      github.com/cessda/cessda.cmv.server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-chestnut-grasshopper.sh
        container: qc.met_shaky-purple-chimpanzee
  QC.Ver:
    repos:
      github.com/cessda/cessda.cmv.server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-chestnut-quoll.sh
        container: qc.ver_gamy-olivine-pig
timeout: 5400
