config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cmv.server:
      branch: main
      repo: https://github.com/cessda/cessda.cmv.server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cmv.server git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-cinnamon-pig.sh
        container: qc.acc_paltry-pear-zonkey
  QC.Doc:
    repos:
      github.com/cessda/cessda.cmv.server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-malachite-quail.sh
        container: qc.doc_breezy-malachite-lionfish
      github.com/cessda/cessda.cmv.server git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-myrtle-tetra.sh
        container: qc.doc_gloppy-fuchsia-slug
      github.com/cessda/cessda.cmv.server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-chocolate-havanese.sh
        container: qc.doc_lovely-olivine-mouse
  QC.Lic:
    repos:
      github.com/cessda/cessda.cmv.server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-sepia-mongoose.sh
        container: qc.lic_cloudy-pear-dhole
  QC.Met:
    repos:
      github.com/cessda/cessda.cmv.server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.surly-pink-salamander.sh
        container: qc.met_hilly-firebrick-jaguar
  QC.Sty:
    repos:
      github.com/cessda/cessda.cmv.server checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-scarlet-malamute.sh
        container: qc.sty_snoopy-gamboge-squirt
      github.com/cessda/cessda.cmv.server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-teal-toucan.sh
        container: qc.sty_hazy-khaki-audemer
  QC.Ver:
    repos:
      github.com/cessda/cessda.cmv.server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-sangria-rabbit.sh
        container: qc.ver_gimpy-mauve-earwig
timeout: 5400
